# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-28 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('cell', models.IntegerField(primary_key=True, serialize=False, verbose_name='Ячейка')),
                ('name', models.CharField(max_length=40, verbose_name='Наименование')),
                ('serial_number', models.CharField(max_length=20, verbose_name='Номер счётчика')),
                ('coeff', models.IntegerField(default=1, verbose_name='Коэффициент')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Ячейка',
                'verbose_name_plural': 'Ячейки',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('pe', models.CharField(max_length=10, verbose_name='Активный приём')),
                ('pi', models.CharField(max_length=10, verbose_name='Активная отдача')),
                ('qe', models.CharField(max_length=10, verbose_name='Реактивный приём')),
                ('qi', models.CharField(max_length=10, verbose_name='Реактивная отдача')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.Cell', verbose_name='Ячейка')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
