# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-29 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PE_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('pe', models.CharField(max_length=10, verbose_name='Активный приём')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.Cell', verbose_name='Ячейка')),
            ],
            options={
                'verbose_name_plural': 'Получасовки активного приёма',
                'verbose_name': 'Активный приём',
            },
        ),
        migrations.CreateModel(
            name='PI_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('pi', models.CharField(max_length=10, verbose_name='Активная отдача')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.Cell', verbose_name='Ячейка')),
            ],
            options={
                'verbose_name_plural': 'Получасовки активной отдачи',
                'verbose_name': 'Активная отдача',
            },
        ),
        migrations.CreateModel(
            name='QE_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('qe', models.CharField(max_length=10, verbose_name='Реактивный приём')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.Cell', verbose_name='Ячейка')),
            ],
            options={
                'verbose_name_plural': 'Получасовки реактивного приёма',
                'verbose_name': 'Реактивный приём',
            },
        ),
        migrations.CreateModel(
            name='QI_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('qi', models.CharField(max_length=10, verbose_name='Реактивная отдача')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.Cell', verbose_name='Ячейка')),
            ],
            options={
                'verbose_name_plural': 'Получасовки реактивной отдачи',
                'verbose_name': 'Реактивная отдача',
            },
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль нагрузки', 'verbose_name_plural': 'Профили нагрузок'},
        ),
    ]
