# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-29 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_auto_20181129_1508'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pe_profile',
            unique_together=set([('cell', 'date', 'time')]),
        ),
        migrations.AlterUniqueTogether(
            name='pi_profile',
            unique_together=set([('cell', 'date', 'time')]),
        ),
        migrations.AlterUniqueTogether(
            name='qe_profile',
            unique_together=set([('cell', 'date', 'time')]),
        ),
        migrations.AlterUniqueTogether(
            name='qi_profile',
            unique_together=set([('cell', 'date', 'time')]),
        ),
    ]
