# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-30 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0003_auto_20181129_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='energy',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Значение'),
        ),
        migrations.AddField(
            model_name='profile',
            name='energy_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Активный приём'), (2, 'Активная отдача'), (3, 'Реактивный приём'), (4, 'Реактивная отдача')], default=1, verbose_name='Тип'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pe',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pi',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='qe',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='qi',
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together=set([('cell', 'date', 'time', 'energy_type')]),
        ),
    ]
