# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-17 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0004_auto_20181130_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='energy',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='energy_type',
            new_name='value_type',
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together=set([('cell', 'date', 'time', 'value_type')]),
        ),
    ]
