# Generated by Django 2.2 on 2020-06-23 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0006_auto_20181220_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='cell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='station.Cell', verbose_name='Ячейка'),
        ),
        migrations.CreateModel(
            name='Rept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('name', models.CharField(max_length=40, verbose_name='Имя')),
                ('value_type', models.PositiveSmallIntegerField(choices=[(1, 'Строка'), (2, 'Целое'), (3, 'Вещественное'), (4, 'JSON'), (5, 'XML')], default=1, verbose_name='Тип')),
                ('value', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Регистр',
                'verbose_name_plural': 'Регистры',
                'unique_together': {('date', 'time', 'name')},
            },
        ),
    ]
